### ISSUE TITLE
Add table turbot_grant

### ISSUE THREAD

**Issue by alexama2012** [turbot/steampipe-plugin-turbot#12]
**References**
Add any related links that will help us understand the resource, including vendor documentation, related GitHub issues, and Go SDK documentation.

I would like to audit who has active grant permissions in my turbot workspace.

**Comment by rajlearner17** [comment]
@alexama2012 Appreciate using Steampipe & suggestions. Nice to see you for testing this out in the Turbot workspace. 
We are looking into this, will keep you updated.

**Comment by rajlearner17** [comment]
@alexama2012 we have a draft branch ready if you would like to test & check, it satisfies the need would be great. [Draft Branch  ](https://github.com/turbot/steampipe-plugin-turbot/tree/issue-12) > Below the steps 

- `git clone https://github.com/turbot/steampipe-plugin-turbot.git ` (if first time closing the repo) 
- `cd steampipe-plugin-turbot`
- run `make`
This should have the `turbot_grant` table, you can run against your turbot workspace cred. 

Let us know in case of any issues.

**Comment by alexama2012** [comment]
FYI Joe.

*Martin** Alexander* | Engineer II, Cloud Operations
*email* ***@***.***  *mobile*
[image: WOW!]
